dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
networks:
  default: development
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c' 
    dao_token: '0xA64F78b1C7fef0FD9Bb22be08c7b0733dc91A86f'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
  my-mainnet-fork:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c' 
    dao_token: '0xA64F78b1C7fef0FD9Bb22be08c7b0733dc91A86f'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}